---
title: "Optimization Test"
output: html_document
---

```{r}
library(ggplot2)
library(reshape2)

#df <- read.csv('/home/nate_black/Dropbox/MIDS/SU/Project/optimization.csv', header =T)
df <- read.csv('/Users/nathanielblack/Dropbox/MIDS/SU/Project/optimization.csv', header =T)

df$Time <- as.numeric(df$Time)

df$ImageSize <- factor(df$ImageSize, levels = c('16x16','32x32','64x64','128x128','256x256'))

df.long <- melt(df, id.vars = c('ImageSize', 'Nodes'))
```

```{r}
image <- ggplot(aes(ImageSize,Time, color = as.factor(Nodes)), data = df) + 
  geom_point(alpha = 0.8, size = 3) +
  ggtitle('Image Size vs Run Time') +
  labs(color ='Nodes') +
  theme_bw()

print(image)
```

```{r}
image2 <- ggplot(aes(ImageSize,Time, color = as.factor(NodeCores)), data = df) + 
  geom_point(alpha = 0.8, size = 3) +
  ggtitle('Image Size vs Run Time') +
  labs(color ='Node Cores') +
  theme_bw()

print(image2)
```



```{r}
image3 <- ggplot(aes(Executors, Time, color = ImageSize), data = df) + 
  geom_point(alpha = 0.8, size = 3) +
  ggtitle('Executors vs Run Time') +
  theme_bw()

print(image3)
```


```{r}
image4 <- ggplot(aes(NodeRAM * Nodes, Time, color = ImageSize), data = df) + 
  geom_point(alpha = 0.8, size = 3) +
  xlab('Total RAM') +
  ggtitle('Total RAM vs Run Time') +
  theme_bw()

print(image4)
```

```{r}
image5 <- ggplot(aes(NodeCores * Nodes, Time, color = NodeRAM), data = df) + 
  geom_point(alpha = 0.8, size = 3) +
  xlab('Total Cores') +
  ggtitle('Total Cores vs Run Time') +
  theme_bw()

print(image5)
```

